Fix: Correct load() call syntax in object_identifier test
The test was calling load(id: 'persistence_test') which breaks with
the new keyword parameter signature. Changed to load('persistence_test').

This is a consequence of changing suffix from optional positional to
keyword parameter. The old syntax load(id: '...') was interpreting the
hash as keyword args, resulting in zero positional args and triggering:
ArgumentError: wrong number of arguments (given 0, expected 1)